package com.example.demo.repository;

import com.example.demo.entity.Orders;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

public interface OrderRepository extends JpaRepository<Orders, Long> {

        // Logic 1:
        // Count total orders placed by a specific customer
        @Query("""
            select count(o)
            from Orders o
            where o.customer.customerId = :customerId
            """)
        Long countOrder(@Param("customerId") Long customerId);


        // Logic 2:
        // Total amount spent by a specific customer
        @Query("""
            select sum(o.totalPrice)
            from Orders o
            where o.customer.customerId = :customerId
            """)
        Double totalAmount(@Param("customerId") Long customerId);


        // Logic 3:
        // Total revenue generated by all orders
        @Query("""
            select sum(o.totalPrice)
            from Orders o
            """)
        Double totalRevenue();


        // Logic 4:
        // Average order value in the system
        @Query("""
            select avg(o.totalPrice)
            from Orders o
            """)
        Double averageOrderValue();


        // Logic 5:
        // Highest order value in the system
        @Query("""
            select max(o.totalPrice)
            from Orders o
            """)
        Double highestOrderValue();


        // Logic 6:
        // Count how many times a product was ordered
        @Query("""
            select count(o)
            from Orders o
            where o.product.productId = :productId
            """)
        Long countOrdersByProduct(@Param("productId") Long productId);


        // Logic 7:
        // Lowest order value in the system
        @Query("""
            select min(o.totalPrice)
            from Orders o
            """)
        Double lowestOrderValue();


        // Logic 8:
        // Total quantity ordered by a specific customer
        @Query("""
            select sum(o.quantityOrdered)
            from Orders o
            where o.customer.customerId = :customerId
            """)
        Integer totalQuantityByCustomer(@Param("customerId") Long customerId);


        // Logic 9:
        // Count orders above a specific amount
        @Query("""
            select count(o)
            from Orders o
            where o.totalPrice > :amount
            """)
        Long countOrdersAboveAmount(@Param("amount") double amount);


        // Logic 10:
        // Revenue generated by a specific product
        @Query("""
            select sum(o.totalPrice)
            from Orders o
            where o.product.productId = :productId
            """)
        Double revenueByProduct(@Param("productId") Long productId);


}